---
- name: The playbook for the Ansible-BOX
  hosts: all
  become: true
  roles:
    - geerlingguy.ntp
    - geerlingguy.docker
    - geerlingguy.nodejs

  vars:
    docker_users:
      - vagrant
    nodejs_version: "18.x"
