---
galaxy_info:
  role_name: base
  author: Javier Juarez
  description: A basic role to take care about some files and packages
  company: IBM Research
  issue_tracker_url: http://github.com/jjuarez/vagrant-ansible-lab/issues/
  license: MIT
  min_ansible_version: "2.4"
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - base
    - common
    - packages
dependencies: []
