---
- name: Install base packages
  package:
    name: "{{base_package_list}}"
    update_cache: true
    state: present
  tags:
    - base
    - packages

- name: bashrc
  ansible.builtin.copy:
    src: files/bash/bashrc
    dest: "{{vagrant_home_dir}}/.bashrc"
    owner: "{{vagrant_user}}"
    group: "{{vagrant_group}}"
    mode: '0640'
  tags:
    - base
    - bash

- name: bash_profile
  ansible.builtin.copy:
    src: files/bash/bash_profile
    dest: "{{vagrant_home_dir}}/.bash_profile"
    owner: "{{vagrant_user}}"
    group: "{{vagrant_group}}"
    mode: '0640'
  tags:
    - base
    - bash
